package by.epam.jwd.sak.avtobase.servlet;

public enum CommandName {
    LOGIN,
    LOGOUT,
    USEREDIT,
    USEREDITBYADMIN,
    EDITCAR,
    REQUESTEDITBYUSER,
    GOTOMAINPAGE,
    REGISTRATION,
    GOTOALLUSERREQUESTPAGE,
    GOTOCREATEREQUEST,
    GOTOALLUSERPAGE,
    GOTOCREATECAR,
    GOTOCREATECOMMENT,
    GOTOALLCOMMENT,
    GOTOALLDRIVER,
    GOTOALLUSERCOMMENT,
    GOTOALLREQUESTPAGE,
    GOTOALLCAR,
    SETDRIVERONREQUEST,
    SETDRIVERONCAR

}