package by.epam.jwd.sak.avtobase.controller;

public enum CommandName {
    LOGIN,
    LOGOUT,
    EDITUSER,
    EDITUSERBYADMIN,
    EDITCAR,
    EDITREQUESTBYUSER,
    REGISTRATION,
    ALLUSERREQUEST,
    ALLREQUESTBYDRIVER,
    CREATEREQUEST,
    ALLUSER,
    CREATECAR,
    CREATECOMMENT,
    ALLCOMMENT,
    ALLDRIVER,
    ALLUSERCOMMENT,
    ALLREQUEST,
    ALLCAR,
    SETDRIVERONREQUEST,
    SETDRIVERONCAR

}