package by.epam.jwd.sak.avtobase.controller;

public enum CommandName {
    LOGIN,
    LOGOUT,
    EDITUSERBYADMIN,
    EDITCAR,
    EDITREQUESTBYUSER,
    EDITSTATUSREQUESTBYDRIVER,
    EDITSTATUSCAR,
    REGISTRATION,
    ALLUSERREQUEST,
    ALLREQUESTBYDRIVER,
    CREATEREQUEST,
    ALLUSER,
    CREATECAR,
    CREATECOMMENT,
    ALLCOMMENT,
    ALLDRIVER,
    ALLUSERCOMMENT,
    ALLREQUEST,
    ALLCAR,
    SETDRIVERONREQUEST,
    SETDRIVERONCAR,
    LANGUAGE,
    WELCOMEPAGE

}